---
add_packages:
  - lm_sensors
  - podman
  - bpytop
  - nano
  - vim
  - micro
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - bash-completion
  - mlocate
  
remove_packages:
  - htop

users:
  - troy

