---
add_packages:
  - lm_sensors
  - podman
  - btop
  - nano
  - vim
  - micro
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - bash-completion
  - cockpit
  - cockpit-podman
  - nfs-utils
  - plocate
  - NetworkManager-tui

remove_packages:
  - htop
  - bpytop

users:
  - troy
