---
- name: install and configure zsh and oh-my-zsh for zsh_users
  hosts: pi
  remote_user: pi
  become: true
  
  vars:
    oh_my_zsh:
      path: .oh-my-zsh
      theme: dst
  tasks:
    - name: clone oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ item.home_dir_base }}{{ item.username }}/{{ oh_my_zsh.path }}"
        clone: true
      become_user: "{{ item.username }}"
      become: true
      loop: "{{ zsh_users }}"
