---
- name: prepare raspberry pis after initial build
  hosts: pi
  become: true

  tasks:
    - name: ensure device boots to console
      file:
        dest: /etc/systemd/system/default.target
        src: /lib/systemd/system/multi-user.target
        state: link
      notify:
        - reboot

    - name: ensure hdmi_force_hotplug=1 is set in /boot/config.txt on pios devices
      lineinfile:
        path: /boot/config.txt
        regex: '^hdmi_force_hotplug'
        insertafter: '#hdmi_force_hotplug'
        line: 'hdmi_force_hotplug=1'
      when: '"pios" in group_names'
      notify:
        - reboot

    - name: update software on device
      apt:
        update_cache: true
        upgrade: full
        autoremove: true
        autoclean: true
      when: ansible_pkg_mgr == "apt"  
      notify:
        - reboot

  handlers:
    - name: reboot
      reboot:
