---
- name: prepare raspberry pis after initial build
  hosts: all
  become: true

  tasks:
    - name: diplay the os family
      debug:
        msg: "{{ ansible_facts['os_family'] }} System"
    
    - name: setup ansible user
      include_tasks: ansible-user.yml
  
    - name: update software
      include_tasks: sw-update.yml
      
    - name: ensure device boots to console
      file:
        dest: /etc/systemd/system/default.target
        src: /lib/systemd/system/multi-user.target
        state: link
      when: '"pi" in group_names'
      notify:
        - reboot

    - name: ensure hdmi_force_hotplug=1 is set in /boot/config.txt on pios devices
      lineinfile:
        path: /boot/config.txt
        regex: '^hdmi_force_hotplug'
        insertafter: '#hdmi_force_hotplug'
        line: 'hdmi_force_hotplug=1'
      when: '"pios" in group_names'
      notify:
        - reboot

  handlers:
    - name: reboot
      reboot:
