---
- name: install/update software on systems
  hosts: all
  become: true

  tasks:
    - name: install and update dnf based software packages
      block:
        - name: update dnf based software
          ansible.builtin.dnf:
            name: '*'
            state: latest
            update_cache: true
          notify: 
            - reboot
        - name: ensure required software is installed on dnf based devices
          ansible.builtin.dnf:
            name: "{{ packages }}"
            state: latest
            update_cache: true
      when: ansible_facts['os_family'] == "RedHat"

    - name: install and update debian based software packages
      block:
        - name: update apt based software
          ansible.builtin.apt:
            update_cache: true
            upgrade: dist
            autoremove: true
          notify: 
            - reboot
        - name: ensure required software is installed on apt based devices
          ansible.builtin.apt:
            name: "{{ packages }}"
            state: latest
            update_cache: true
      when: ansible_facts['os_family'] == "Debian"

    - name: install and update pacman based software packages
      block:
        - name: update pacman based software
          community.general.pacman:
            update_cache: true
            upgrade: true
          notify: 
            - reboot
        - name: ensure required software is installed on pacman based devices
          community.general.pacman:
            name: "{{ packages }}"
            state: latest
            update_cache: true    
      when: ansible_facts['os_family'] == "Archlinux"

  handlers:
    - name: reboot
      ansible.builtin.reboot:
