---
- name: install/update software on systems
  hosts: all
  become: true

  tasks:
    - name: create troy user
      ansible.builtin.user:
        name: troy
        state: present
        groups: nopasswd
        shell: /bin/zsh

    - name: copy ssh key to troy authorized keys
      ansible.posix.authorized_key:
        user: troy
        key: "{{ lookup('file', '/home/troy/data/keys/ssh/id_ed25519.pub') }}"
        state: present
        exclusive: true
