---
add_packages:
  - cockpit
  - lm_sensors
  - podman
  - bpytop
  - nano
  - vim
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - bash-completion
  - httpd
  - nginx
  - haproxy
  - nfs-utils
  - mlocate
  
remove_packages:
  - htop

users:
  - troy
